IQAIcom/brain

.changeset/tough-suns-guess.md, packages/agent/src/default-charecter.ts, packages/plugin-sequencer/src/actions/sequencer.ts
- Adds quick fix for: update sequencer and agent prompts
=> update sequencer and agent prompts

.cursor/rules/plugin-creation.mdc, .cursor/rules/plugin-docs.mdc, .cursor/rules/plugin-readme.mdc, apps/docs/src/content/docs/getting-started/quickstart.mdx, apps/docs/src/content/docs/plugins/atp.mdx, apps/docs/src/content/docs/plugins/fraxlend.mdx, apps/docs/src/content/docs/plugins/heartbeat.mdx, apps/docs/src/content/docs/plugins/odos.mdx, apps/docs/src/content/docs/plugins/overview.mdx, apps/playground/src/index.ts, packages/agent/README.md, packages/agent/src/agent.ts, packages/agent/src/builder.ts, packages/agent/src/index.ts, packages/agent/src/types.ts
fixes https://github.com/IQAIcom/issues/issues/36
=> not need eliza core in documentation

.changeset/bright-walls-breathe.md, packages/agent/README.md, packages/agent/src/agent.ts, packages/agent/src/builder.ts, packages/agent/src/index.ts, packages/agent/src/types.ts
- Adds quick fix for: direct model name export from elizaos
=> direct model name export from elizaos

.changeset/two-years-tan.md, packages/agent/src/index.ts
- Adds quick fix for: export model name as value instead of type
=> export model name as value instead of type

.changeset/large-cherries-bathe.md, apps/docs/astro.config.mjs, apps/docs/src/content/docs/plugins/mcp.mdx, apps/docs/src/content/docs/plugins/overview.mdx, apps/playground/package.json, apps/playground/src/index.ts, packages/plugin-bamm/README.md, packages/plugin-mcp/README.md, packages/plugin-mcp/package.json, packages/plugin-mcp/src/index.ts, packages/plugin-mcp/src/lib/create-action.ts, packages/plugin-mcp/src/services/generate-tool-template.ts, packages/plugin-mcp/src/services/input-parser.ts, packages/plugin-mcp/src/services/mcp-client.ts, packages/plugin-mcp/src/types.ts, packages/plugin-mcp/tsconfig.json, packages/plugin-mcp/tsup.config.ts, pnpm-lock.yaml
- Adds plugin-mcp to communicate with mcp servers
- Added readme
- Added astro doc
- closes https://github.com/IQAIcom/issues/issues/38
=> Adds plugin-mcp

apps/docs/src/content/docs/index.mdx
=> added link to iqai.com

.changeset/tame-badgers-allow.md, apps/docs/src/content/docs/plugins/heartbeat.mdx, packages/plugin-heartbeat/README.md, packages/plugin-heartbeat/src/services/heartbeat.ts, packages/plugin-heartbeat/src/types.ts
Closes https://github.com/IQAIcom/issues/issues/76
- Adds callback support for heartbeat plugin
=> Add support for callback in Heartbeat service

.changeset/swift-scissors-remain.md, apps/playground/src/index.ts, packages/plugin-heartbeat/src/services/heartbeat.ts
- Adds quick fix for: fix callbacks not being shown on tg/twitter client from heartbeat plugin
=> fix callbacks not being shown on tg/twitter client from heartbeat plugin

.changeset/heavy-crews-turn.md, apps/docs/astro.config.mjs, apps/docs/src/content/docs/plugins/overview.mdx, apps/docs/src/content/docs/plugins/wallet.mdx, apps/playground/package.json, apps/playground/src/index.ts, packages/plugin-wallet/README.md, packages/plugin-wallet/package.json, packages/plugin-wallet/src/actions/get-holdings.ts, packages/plugin-wallet/src/actions/get-transactions.ts, packages/plugin-wallet/src/index.ts, packages/plugin-wallet/src/lib/chain-utils.ts, packages/plugin-wallet/src/lib/format-number.ts, packages/plugin-wallet/src/lib/templates.ts, packages/plugin-wallet/src/services/get-holdings.ts, packages/plugin-wallet/src/services/get-transactions.ts, packages/plugin-wallet/src/services/input-parser.ts, packages/plugin-wallet/src/types.ts, packages/plugin-wallet/tsconfig.json, packages/plugin-wallet/tsup.config.ts, pnpm-lock.yaml
closes https://github.com/IQAIcom/issues/issues/82
=> Adds Plugin wallet

.changeset/itchy-boats-matter.md, packages/plugin-mcp/src/services/mcp-client.ts
- added client version, fixing mcp error -32603
=> adds client version, fixing mcp error -32603

.github/workflows/push.yml, README.md, biome.json, package.json, packages/plugin-atp/package.json, packages/plugin-atp/src/actions/agent-stats.ts, packages/plugin-atp/src/actions/get-agents.ts, packages/plugin-atp/src/services/agent-stats.ts, packages/plugin-atp/src/services/get-agents.ts, packages/plugin-atp/src/tests/actions/getAgent.test.ts, packages/plugin-atp/src/tests/actions/getAgentPostionsAction.test.ts, packages/plugin-atp/src/tests/actions/getAgentStatsAction.test.ts, packages/plugin-atp/src/tests/services/agentPostions.test.ts, packages/plugin-atp/src/tests/services/getStats.test.ts, packages/plugin-fraxlend/package.json, packages/plugin-fraxlend/src/tests/services/add-collateral.test.ts, packages/plugin-fraxlend/src/tests/services/borrow.test.ts, packages/plugin-fraxlend/src/tests/services/withdraw.test.ts, packages/plugin-odos/package.json, packages/plugin-odos/src/tests/actions/getQuoteAction.test.ts, packages/plugin-odos/src/tests/actions/swap.test.ts, packages/plugin-odos/src/tests/services/assemble.test.ts, packages/plugin-odos/src/tests/services/execute-swap.test.ts, packages/plugin-odos/src/tests/services/get-quote.test.ts, packages/plugin-sequencer/package.json, packages/plugin-sequencer/src/tests/sequencer.test.ts, pnpm-lock.yaml, test-plugins.sh
Tests service and actions of SEQUENCER, ATP, ODOS & FRAXLEND
```
pnpm test:plugins
```
closes https://github.com/IQAIcom/issues/issues/1
=> Plugins test

.changeset/breezy-owls-run.md, packages/agent/src/builder.ts
- Adds quick fix for: error when agent without db
=> error when agent without db

packages/adapter-sqlite/README.md, packages/adapter-sqlite/package.json, packages/adapter-sqlite/src/index.ts, packages/adapter-sqlite/tsconfig.json, packages/adapter-sqlite/tsup.config.ts, pnpm-lock.yaml
- Adds quick fix for: sqlite adapter wrapper
=> sqlite adapter wrapper

apps/docs/src/content/docs/adapters/sqlite.mdx, apps/docs/src/content/docs/clients/discord.mdx, apps/docs/src/content/docs/clients/telegram.mdx, apps/docs/src/content/docs/clients/twitter.mdx, apps/docs/src/content/docs/getting-started/agent-creation.mdx, apps/docs/src/content/docs/getting-started/deployment.mdx, apps/docs/src/content/docs/getting-started/quickstart.mdx, apps/playground/package.json, apps/playground/src/index.ts, packages/agent/README.md, packages/agent/package.json, pnpm-lock.yaml
- Enables usage of SqliteDatabaseAdapter from @iqai/adapter-sqlite, which should simplify the api a lot
=> Update SqliteDatabaseAdapter dependency to @iqai/adapter-sqlite

.changeset/eighty-deers-explain.md, packages/plugin-heartbeat/src/lib/template.ts, packages/plugin-heartbeat/src/services/heartbeat.ts, packages/plugin-heartbeat/src/types.ts
- Adds quick fix for: heartbeat multiple clients
=> heartbeat multiple clients

.changeset/olive-dots-happen.md, packages/plugin-heartbeat/src/services/heartbeat.ts
- Adds quick fix for: remove console log in heartbeat
=> remove console log in heartbeat

.changeset/strange-forks-film.md, apps/playground/package.json, apps/playground/src/index.ts, packages/plugin-sequencer/src/services/sequencer.ts, pnpm-lock.yaml
- Adds quick fix for: fixes embedding miss match error in sequencer
=> fixes embedding miss match error in sequencer

.changeset/real-worms-sniff.md, apps/docs/src/content/docs/plugins/atp.mdx, packages/plugin-abi/tsconfig.json, packages/plugin-atp/README.md, packages/plugin-atp/src/actions/add-agent-log.ts, packages/plugin-atp/src/actions/get-agent-logs.ts, packages/plugin-atp/src/constants.ts, packages/plugin-atp/src/index.ts, packages/plugin-atp/src/lib/templates.ts, packages/plugin-atp/src/services/agent-logs.ts, packages/plugin-atp/src/types.ts, packages/plugin-atp/tsconfig.json, packages/plugin-heartbeat/tsconfig.json, packages/plugin-sequencer/tsconfig.json
Closes https://github.com/IQAIcom/issues/issues/183 when merged.
- Added add & get agent logs to the plugin-atp
- Updated plugin config to take in apiKey
- Updated readme & astro docs
=> Adds add/get agent logs to plugin-atp

.changeset/dull-rings-occur.md, packages/plugin-atp/src/actions/add-agent-log.ts, packages/plugin-atp/src/actions/agent-positions.ts, packages/plugin-atp/src/actions/buy.ts, packages/plugin-atp/src/actions/get-agent-logs.ts, packages/plugin-atp/src/actions/sell.ts, packages/plugin-atp/src/services/agent-logs.ts
- Added early returns in actions if required wallet param is not provided.
- Updated the format logs method to include txHash
=> Updates to plugin-atp

.changeset/gorgeous-bags-punch.md, apps/docs/src/content/docs/plugins/wiki.mdx, apps/playground/src/index.ts, packages/plugin-wiki/README.md, packages/plugin-wiki/src/actions/get-created-wikis.ts, packages/plugin-wiki/src/actions/get-edited-wikis.ts, packages/plugin-wiki/src/actions/get-wiki-activities.ts, packages/plugin-wiki/src/index.ts, packages/plugin-wiki/src/lib/queries.ts, packages/plugin-wiki/src/services/get-created-wikis.ts, packages/plugin-wiki/src/services/get-edited-wikis.ts, packages/plugin-wiki/src/services/get-user-wiki-activities.ts, packages/plugin-wiki/src/services/get-wiki.ts
- removed get-latest-wikis action and replaced it with get-edited-wikis, get-created-wikis, get-user-wiki-activities
- better formatting for format methods in service classes
=> updates to plugin wiki

.changeset/clever-crews-nail.md, apps/docs/src/content/docs/plugins/wiki.mdx, packages/plugin-wiki/README.md, packages/plugin-wiki/src/lib/constants.ts, packages/plugin-wiki/src/services/get-edited-wikis.ts, packages/plugin-wiki/src/services/get-user-wiki-activities.ts
- show revision links for wiki edits instead of live wiki link
=> plugin-wiki: revision links for wiki edits

apps/docs/src/content/docs/getting-started/deployment.mdx
_Closes https://github.com/IQAIcom/issues/issues/230 when this PR merged._
=> Added GCP Guide: web interface and CLI
